# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objinfo',
            name='zip',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
