# Generated by Django 2.0.2 on 2018-04-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('pers', '0003_auto_20180420_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ustags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pers.Objinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth')),
            ],
        ),
    ]
